### ISSUE TITLE
Add a rule for inline comment

### ISSUE THREAD

**Issue by ggrossetie** [highlightjs/highlightjs-cypher#5]
In the following Cypher query `// returns all nodes in the graph` is a comment:

```cypher
MATCH (n) // returns all nodes in the graph
RETURN n
```

I think we should add the rule `hljs.C_LINE_COMMENT_MODE`.

**Comment by gusbemacbe** [comment]
Done, see if it is correct.

**Comment by ggrossetie** [comment]
Yes, it's working as expected: https://github.com/highlightjs/highlightjs-cypher/pull/8/files#diff-45e0960675115e8bef509b25617265a6

We can close this issue.
