### ISSUE TITLE
Alias with backtick should be a string

### ISSUE THREAD

**Issue by ggrossetie** [highlightjs/highlightjs-cypher#6]
In the following Cypher query \`birth year` should be a string:

```cypher
MATCH (p:Person {born: 1965})
RETURN p.name AS name, p.born AS `birth year`
```

**Comment by gusbemacbe** [comment]
I really did not understand what you explained. But you are free to make a PR.

**Comment by ggrossetie** [comment]
I meant `` `birth year` `` is an alias name so we should mark this token as a "string", similar to `'birth year'` or `"birth year"`.
Currently this token is not recognized (plain text).
