### ISSUE TITLE
Add call as a keyword

### ISSUE THREAD

**Issue by ggrossetie** [highlightjs/highlightjs-cypher#7]
For instance:

```cypher
CALL db.propertyKeys
```

**Comment by gusbemacbe** [comment]
Done, see if it is correct.

**Comment by ggrossetie** [comment]
> Done, see if it is correct.

I can't find the commit, did you push on GitHub? Am I missing something?

**Comment by gusbemacbe** [comment]
Ah, I pushed to the wrong branch.

**Comment by gusbemacbe** [comment]
Done, @Mogztter.

**Comment by ggrossetie** [comment]
@gusbemacbe Thanks, it's looking good. I will add a test for it once https://github.com/highlightjs/highlightjs-cypher/pull/8 is merged.

**Comment by gusbemacbe** [comment]
Done, @Mogztter.
